app.name: tbk-spring-boot-bitcoin-starter-demo
app.description: A spring boot bitcoin demo application

spring.application.name: 'tbk-spring-boot-bitcoin-starter-demo'
spring.profiles.active: production
spring.http.log-request-details: false

server.port: 8080
server.use-forward-headers: true
server.compression.enabled: true

management.server.port: 9001
management.server.servlet.context-path: /actuator

# LOGGING
logging.file.path: ./var/log
logging.file.name: application.log
logging.config: classpath:logback.xml
logging.level.org.springframework: INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
#logging.level.web: DEBUG

org.tbk.spring.bitcoin.testcontainer:
  enabled: true
  rpcuser: myrpcuser
  rpcpassword: correcthorsebatterystaple
  commands:
    # [debug]
    # Append comment to the user agent string.
    - '-uacomment=tbk-spring-bitcoin-testcontainer-example'
    # Allows you to test address relay on localhost.
    - '-addrmantest=1'
    # Run checks every <n> transactions.
    - '-checkmempool=1'
    # Send trace/debug info to console instead of debug.log.
    - '-printtoconsole=1'
    # Log transaction fee per kB when mining blocks.
    - '-printpriority=1'
    # Enable debug logging for all categories.
    - '-debug=1'
    # Log IP Addresses in debug output.
    - '-logips=1'
    # [rpc]
    # Number of seconds after which an uncompleted RPC call will time out
    - '-rpcservertimeout=10' # default is 30

org.tbk.bitcoin.jsonrpc:
  network: regtest
  rpchost: http://localhost
  rpcport: 18443
  rpcuser: myrpcuser
  rpcpassword: correcthorsebatterystaple
